# Generated by Django 5.1.3 on 2024-12-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
